# Alacritty toml configuration
# Ryan McMillan 2024

import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[window]

opacity = 0.85

padding.x = 10
padding.y = 10

decorations = "Buttonless"
decorations_theme_variant = "Dark"

[font]

normal.family = "Iosevka Term SS04"
bold.family = "Iosevka Term SS04"
italic.family = "Iosevka Term SS04"
bold_italic.family = "Iosevka Term SS04"

size = 15.0

